Chunk Mesh Generation Optimization
obiwac/python-minecraft-clone pull request #96
Opened 2023-05-09 14:46 UTC by OrdinaryDev83

- added a return case if the block is surrounded by 8 full blocks
- (revert) changed it to be parallelized with Thread Pooling (which I gave up because the performance was worse)

Changes suggested by ChatGPT 4, coded and adapted it.
Tell me if you see an improvement in performance.

2023-05-10 00:33 UTC, obiwac commented
Hey! Thanks for the PR :)

I saw you made 2 others, #94 and #95 - could you clarify which ones you'd like reviewed and potentially merged?

2023-05-11 20:26 UTC, obiwac requested changes

2023-05-11 20:26 UTC, obiwac commented on community/subchunk.py
> +								self.add_face(i, pos, parent_lpos, block_number, block_type)
Small nit: missing newline here.

2023-05-14 06:45 UTC, OrdinaryDev83 commented
Am I supposed to commit the change ?

2023-05-14 11:56 UTC, obiwac commented
yes

2024-08-05 14:59 UTC, closed without merging